# Generated by Django 5.2.4 on 2025-09-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userprofile_allergies_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='cooking_time',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='userhistory',
            old_name='cuisine',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='meal_name',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='protein_source',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='restriction',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='steps',
            field=models.TextField(null=True),
        ),
    ]
