# Generated by Django 5.2.4 on 2025-09-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_cooking_time_userhistory_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='budget',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='duration',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
